#include "formula_parser.h"

#include "mpc/mpc.h"

#include <stdio.h>
#include <stdlib.h> /* For atof */
#include <string.h> /* For strcmp */


/*
 * Forward declarations for AST evaluation.
 */
static double
eval_ast(mpc_ast_t const * const tree, double const x_value);


/*
 * @brief Parses and evaluates a mathematical formula.
 *
 * This function takes a formula string (e.g., "x * (x + 2)"), substitutes
 * the value for 'x', and computes the result.
 *
 * @param formula The mathematical formula to evaluate.
 * @param x The value to substitute for the variable 'x'.
 * @param result A pointer to a double where the result will be stored.
 * @return 0 on success, a non-zero value on parsing or evaluation error.
 */
int
parse_and_evaluate(char const * const formula, double const x, double * const result)
{
    /*
     * Define the grammar for mathematical expressions.
     * To handle PEG parser behavior, we define float and int separately
     * and try to match the more specific 'float' rule first.
     */
    mpc_parser_t * Float    = mpc_new("float");
    mpc_parser_t * Int      = mpc_new("int");
    mpc_parser_t * Number   = mpc_new("number");
    mpc_parser_t * Variable = mpc_new("variable");
    mpc_parser_t * Factor   = mpc_new("factor");
    mpc_parser_t * Term     = mpc_new("term");
    mpc_parser_t * Expr     = mpc_new("expr");
    mpc_parser_t * Formula  = mpc_new("formula");

    mpca_lang(MPCA_LANG_DEFAULT,
        "  float    : /-?[0-9]+\\.[0-9]+/ ;                      "
        "  int      : /-?[0-9]+/ ;                              "
        "  number   : <float> | <int> ;                         "
        "  variable : \"x\" ;                                   "
        "  factor   : <number> | <variable> | '(' <expr> ')' ;  "
        "  term     : <factor> (('*' | '/') <factor>)* ;        "
        "  expr     : <term> (('+' | '-') <term>)* ;            "
        "  formula  : /^/ <expr> /$/ ;                          ",
        Float, Int, Number, Variable, Factor, Term, Expr, Formula);

    mpc_result_t parse_result;
    int          ret_code = -1; /* Assume failure */

    if (mpc_parse("<input>", formula, Formula, &parse_result))
    {
        mpc_ast_t * const ast = parse_result.output;
        double const evaluated_result = eval_ast(ast->children[1], x);

        if (NULL != result)
        {
            *result = evaluated_result;
        }

        mpc_ast_delete(ast);
        ret_code = 0; /* Success */
    }
    else
    {
        /*
         * Parsing failed. Print error for debugging.
         */
        mpc_err_print(parse_result.error);
        mpc_err_delete(parse_result.error);
    }

    mpc_cleanup(8, Float, Int, Number, Variable, Factor, Term, Expr, Formula);

    return ret_code;
}


/*
 * @brief Recursively evaluates the Abstract Syntax Tree (AST) generated by mpc.
 *
 * This function traverses the AST, performing calculations based on the
 * defined grammar rules and substituting the value for 'x'.
 *
 * @param tree The root of the AST or a sub-tree to evaluate.
 * @param x_value The numerical value to substitute for the variable 'x'.
 * @return The calculated numerical result of the AST.
 */
static double
eval_ast(mpc_ast_t const * const tree, double const x_value)
{
    /*
     * If the node is a number (float or int), it is a terminal leaf. Return its value.
     */
    if ((0 != strstr(tree->tag, "float")) || (0 != strstr(tree->tag, "int")))
    {
        return atof(tree->contents);
    }
    if (0 != strstr(tree->tag, "variable"))
    {
        return x_value;
    }

    /*
     * If the expression is wrapped in parentheses, e.g., "(<expr>)", its value is
     * the evaluation of the inner expression, which is the second child.
     */
    if (0 == strcmp(tree->children[0]->contents, "("))
    {
        return eval_ast(tree->children[1], x_value);
    }

    /*
     * Otherwise, it's an operator expression. Evaluate the first child as the
     * starting value.
     */
    double left_operand = eval_ast(tree->children[0], x_value);

    /*
     * Iterate over the remaining children, which come in (operator, operand) pairs.
     */
    for (int i = 1; i < tree->children_num; i += 2)
    {
        mpc_ast_t const * const operator_node = tree->children[i];
        mpc_ast_t const * const right_operand_node = tree->children[i + 1];

        char const * const op = operator_node->contents;
        double const right_operand = eval_ast(right_operand_node, x_value);

        if (0 == strcmp(op, "+"))
        {
            left_operand += right_operand;
        }
        else if (0 == strcmp(op, "-"))
        {
            left_operand -= right_operand;
        }
        else if (0 == strcmp(op, "*"))
        {
            left_operand *= right_operand;
        }
        else if (0 == strcmp(op, "/"))
        {
            /*
             * Basic division by zero check.
             */
            if (0.0 == right_operand)
            {
                fprintf(stderr, "Error: Division by zero\n");
                return 0.0; /* Or some error indicator like NAN */
            }

            left_operand /= right_operand;
        }
    }

    return left_operand;
}